apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: hmm
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine3.18
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Namespace
metadata:
  name: hmm
